### ISSUE TITLE
MISP to use external database?

### ISSUE THREAD

**Issue by khalavak** [coolacid/docker-misp#173]
Hello,
I had a look at https://github.com/coolacid/docker-misp/issues/158 regarding MySQL server user/password and have the following question / request: 
Is it possible, and how, to use an external database for MISP? In my case, I would like to deploy MISP in Azure and use Azures Mysql/MariaDB service for the database so that I don't have to care about the DB at all and let Azure handle the database for me and be able to scale if needed?

Is is just possible to change the environment variable: 

```
environment:
      # Database Configuration (And their defaults)
      - "MYSQL_HOST=external-database-host.example.com"
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=SUPERSECRETPASSWORD"#      
      - "MYSQL_DATABASE=misp"
```

...and if using external database, is is possible to remove the mysql database installation via docker completely? And how? Just remov the docker db: instance from the docker-compose.yml ?

```
db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE Prevent runaway mysql log
```
      -
